apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkinsdeploy
  name: jenkinsdeploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkinsdeploy
  template:
    metadata:
      labels:
        app: jenkinsdeploy
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        ports:
                - name: http-port
                  containerPort: 8080
                - name: jnlp-port
                  containerPort: 31000
        volumeMounts:
                - name: jenkins-vol
                  mountPath: {{ .Values.mountPath }}
      volumes:
              - name: jenkins-vol
                emptyDir: {}
