apiVersion: v1
kind: Service
metadata:
        name: jenkinssvc
spec:
        type: NodePort
        ports:
                - port: {{ .Values.port }}
                  targetPort: 8080
                  nodePort: {{ .Values.nodePort }}
        selector:
                app: jenkinsdeploy
